name: fitlip_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Built-in localization and internationalization
  flutter_localizations:
    sdk: flutter

  intl:
  cupertino_icons: ^1.0.8
  cached_network_image:
  google_fonts:
  image_picker:
  dio:
  table_calendar:
  shared_preferences:
  otp_text_field:
  flutter_screenutil:
  curved_navigation_bar:
  flutter_dotenv:
  path_provider:
  path:
  http_parser:
  image:
  http:
  connectivity_plus:
  internet_connection_checker:
  package_info_plus:
  url_launcher:
  font_awesome_flutter:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter:

  uses-material-design: true

  # Assets
  assets:
    - assets/Images/
    - assets/Icons/
    - .env

  # Localization config
  generate: true # This tells Flutter to auto-generate localization files

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Images/application_logo.png"
  remove_alpha_ios: true
